# Generated by Django 5.0.7 on 2024-12-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulseAndPenApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
